on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Running XSLTLint on itself
        shell: bash
        run: xsltproc --xinclude $GITHUB_ACTION_PATH/XSLTLint.xslt $GITHUB_ACTION_PATH/XSLTLint.xslt

