name: 'XSLT Linter'
description: 'Check an XSLT stylesheet for some common mistakes'
inputs:
  xslt-file:
    description: 'The stylesheet file to check'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check file
      id: linting
      shell: bash
      run: xsltproc --xinclude XSLTLint.xslt $INPUT_XSLT_FILE | echo "report=$@" >> $GITHUB_OUTPUT
      env:
        INPUT_XSLT_FILE: ${{ inputs.xslt-file }}
    - name: Report linting status
      id: reporting
      shell: bash
      run: |
        if [[ "${{ steps.linting.outputs.report }}" == "" ]]; then
          exit 0
        else
          echo "$GITHUB_OUTPUT"
          exit 0
        fi
