name: 'XSLT Linter'
description: 'Check an XSLT stylesheet for some common mistakes'
inputs:
  xslt-file:
    description: 'The stylesheet file to check'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check file
      shell: bash
      run: xsltproc --xinclude XSLTLint.xslt $INPUT_XSLT_FILE
      env:
        INPUT_XSLT_FILE: ${{ inputs.xslt-file }}
