on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Running XSLTLint on itself
        run: xsltproc --xinclude ${{ github.workspace }}/XSLTLint.xslt ${{ github.workspace }}/XSLTLint.xslt
  
