on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Running XSLTLint on itself
        run: |
          cd ${{ github.action_path }}/../..
          xsltproc --xinclude XSLTLint.xslt XSLTLint.xslt
  
